/* 주문량이 많은 아이스크림들 조회하기 */

-- JOIN -- 

WITH ORDER_INFO AS (
    SELECT 
        FH.FLAVOR, 
        FH.TOTAL_ORDER + JULY.TOTAL_ORDER AS TOTAL_ORDER
    FROM FIRST_HALF FH
        JOIN (
            SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
            FROM JULY
            GROUP BY FLAVOR
        ) AS JULY
        ON FH.FLAVOR = JULY.FLAVOR
    ORDER BY TOTAL_ORDER DESC
)


-- UNION ALL --

WITH ORDER_INFO AS (
    SELECT 
        FLAVOR,
        SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM (
        SELECT * FROM FIRST_HALF
        UNION ALL 
        SELECT * FROM JULY
    ) AS T
    GROUP BY FLAVOR
)

SELECT FLAVOR
FROM ORDER_INFO
ORDER BY TOTAL_ORDER DESC
LIMIT 3