/* 그룹별 조건에 맞는 식당 목록 출력하기 */

WITH REVIEW_RNK AS(
    SELECT MEMBER_ID, RANK() OVER(ORDER BY REVIEW_COUNT DESC) AS RNK
    FROM (
        SELECT MEMBER_ID, COUNT(MEMBER_ID) AS REVIEW_COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID) T
    ORDER BY RNK ASC
)

SELECT 
    M.MEMBER_NAME, 
    R.REVIEW_TEXT, 
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M 
    JOIN REST_REVIEW R
    ON M.MEMBER_ID = R.MEMBER_ID
WHERE R.MEMBER_ID IN (SELECT MEMBER_ID
                      FROM REVIEW_RNK
                      WHERE RNK = 1)
ORDER BY REVIEW_DATE ASC, R.REVIEW_TEXT ASC


