/* 5월 식품들의 총매출 조회하기 */

WITH FOOD_ORDER_MAY AS (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
    GROUP BY PRODUCT_ID
)

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, PRICE * AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT P 
    JOIN FOOD_ORDER_MAY O
    ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC