/* 상품 별 오프라인 매출 구하기 */

WITH SALES AS (
    SELECT 
        PRODUCT_ID, 
        SUM(SALES_AMOUNT) AS SALES_AMOUNT
    FROM OFFLINE_SALE      
    GROUP BY PRODUCT_ID
)

SELECT 
    P.PRODUCT_CODE, 
    (P.PRICE * S.SALES_AMOUNT) AS SALES
FROM PRODUCT P 
    JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE ASC