/* 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기 */

WITH CAR_RENTAL_INFO AS (
    SELECT 
        CAR_ID, 
        C.CAR_TYPE, 
        CASE 
            WHEN PLAN_ID IS NULL THEN DAILY_FEE * 30
            ELSE DAILY_FEE * 30 * (100 - DISCOUNT_RATE) DIV 100
        END AS MONTHLY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C
        LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
        ON C.CAR_TYPE = D.CAR_TYPE
    WHERE C.CAR_TYPE IN ('SUV', '세단') 
      AND DURATION_TYPE = '30일 이상'
)


-- NOT IN --

SELECT 
    CAR_ID, 
    CAR_TYPE, 
    MONTHLY_FEE AS FEE
FROM CAR_RENTAL_INFO C
WHERE MONTHLY_FEE >= 500000 
  AND MONTHLY_FEE < 2000000
  AND CAR_ID NOT IN (
        SELECT DISTINCT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE < '2022-11-30' AND END_DATE > '2022-11-01'
    )
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC


-- NOT EXISTS --
SELECT 
    CAR_ID, 
    CAR_TYPE, 
    MONTHLY_FEE AS FEE
FROM CAR_RENTAL_INFO C
WHERE MONTHLY_FEE >= 500000 
  AND MONTHLY_FEE < 2000000
  AND NOT EXISTS (
      SELECT 1
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
      WHERE H.CAR_ID = C.CAR_ID
        AND START_DATE < '2022-11-30' 
        AND END_DATE > '2022-11-01'
    )
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
