/* FrontEnd 개발자 찾기 */

SELECT 
    D.ID, 
    D.EMAIL, 
    D.FIRST_NAME, 
    D.LAST_NAME
FROM DEVELOPERS D
    JOIN SKILLCODES S
    ON (S.CODE & D.SKILL_CODE) > 0 AND S.CATEGORY = 'Front End'
GROUP BY D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
ORDER BY D.ID ASC