/* 년, 월, 성별 별 상품 구매 회원 수 구하기 */
 
SELECT
    YEAR(OS.SALES_DATE) AS YEAR, 
    MONTH(OS.SALES_DATE) AS MONTH, 
    UI.GENDER AS GENDER,
    COUNT(DISTINCT UI.USER_ID) AS USERS

FROM USER_INFO UI
    JOIN ONLINE_SALE OS
    ON UI.USER_ID = OS.USER_ID

WHERE UI.GENDER IS NOT NULL

GROUP BY UI.GENDER, YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE)

ORDER BY YEAR, MONTH, GENDER

/*
-- 문제 파악 --
• Lv4 이상의 난이도부터는 문제를 파악하는 것도 중요
• COUNT(DISTINCT USER_ID) 가 관건이었음
*/