/* 카테고리 별 도서 판매량 집계하기 */

SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALE
FROM BOOK B
    JOIN BOOK_SALES BS
    ON B.BOOK_ID = BS.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = '2022-01'
GROUP BY CATEGORY
ORDER BY CATEGORY ASC