/* 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기 */

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE 
    START_DATE BETWEEN '2022-08-01' AND '2022-10-31' 
    AND CAR_ID IN ( SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31' AND CAR_ID
                    GROUP BY CAR_ID HAVING COUNT(*) >= 5)
GROUP BY CAR_ID, MONTH
ORDER BY MONTH ASC, CAR_ID DESC


/* 
## CTE ##
# Common Table Expression
# 하나의 쿼리문 범위 내에서만 존재하며, 여러번 참조될 수 있는 이름이 지정된 일회성 테이블
# WITH 절을 통해 테이블 이름과, 들어갈 컬럼을 지정
*/

WITH
CAR_RENTAL_HISTORY AS (
    SELECT CAR_ID, MONTH(START_DATE) AS MONTH
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31' AND CAR_ID),

FILTERED AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_HISTORY
    GROUP BY CAR_ID HAVING COUNT(*) >= 5)

SELECT A.MONTH, A.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_HISTORY A, FILTERED B
WHERE A.CAR_ID IN (B.CAR_ID)
GROUP BY A.MONTH, A.CAR_ID
ORDER BY A.MONTH ASC, A.CAR_ID DESC