/* 조건에 맞는 도서 리스트 출력하기 */

SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = 2021 AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE ASC

/*
-- DATE 함수 --
• DATE_FORMAT()
• YEAR, MONTH, DAY, HOUR, MINUTE, SECOND
• NOW, CURDATE, CURTIME
*/