/* 연도별 대장균 크기의 편차 구하기 */

SELECT YEAR, (MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV, ID

FROM (
    SELECT ID, SIZE_OF_COLONY, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA) E1 
NATURAL JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR) E2

ORDER BY YEAR ASC, YEAR_DEV ASC