/* 식품분류별 가장 비싼 식품의 정보 조회하기 */

SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT CATEGORY, PRODUCT_NAME, PRICE, RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RNK
    FROM FOOD_PRODUCT
) FP
WHERE RNK = 1 AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY PRICE dESC