/* 즐겨찾기가 가장 많은 식당 정보 출력하기 */

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RNK
    FROM REST_INFO
    ) RI
WHERE RNK = 1
ORDER BY FOOD_TYPE DESC