/* 저자 별 카테고리 별 매출액 집계하기 */

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, BS.CATEGORY, SUM(BS.TOTAL_SALES) AS TOTAL_SALES
FROM AUTHOR A 
    JOIN (
        SELECT B.BOOK_ID, AUTHOR_ID, CATEGORY, PRICE, PRICE * SUM(SALES) AS TOTAL_SALES
        FROM BOOK B
            JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
        WHERE S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
        GROUP BY BOOK_ID ) BS
    ON A.AUTHOR_ID = BS.AUTHOR_ID
GROUP BY A.AUTHOR_ID, BS.CATEGORY
ORDER BY A.AUTHOR_ID ASC, BS.CATEGORY DESC

/*
문법보단 문제를 이해하는 것이 포인트
*/