/* 조건에 맞는 사용자와 총 거래금액 조회하기 */

SELECT U.USER_ID, U.NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B
    JOIN USED_GOODS_USER U
    ON B.WRITER_ID = U.USER_ID
WHERE STATUS = 'DONE'
GROUP BY U.USER_ID HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES ASC