/* 조건에 맞는 사원 정보 조회하기 */

SELECT G.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E 
    JOIN (
        SELECT EMP_NO, SUM(SCORE) AS SCORE
        FROM HR_GRADE
        WHERE YEAR = 2022
        GROUP BY EMP_NO
        ) G
    ON E.EMP_NO = G.EMP_NO
ORDER BY G.SCORE DESC
LIMIT 1