/* 조건에 부합하는 중고거래 댓글 조회하기 */

SELECT UGB.TITLE, UGB.BOARD_ID, UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS, DATE_FORMAT(UGR.CREATED_DATE,"%Y-%m-%d") as CREATED_DATE
FROM USED_GOODS_BOARD UGB JOIN USED_GOODS_REPLY UGR ON UGB.BOARD_ID = UGR.BOARD_ID
WHERE UGB.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY CREATED_DATE ASC, UGB.TITLE ASC


/* 
-- JOIN ON --
ON 절을 사용해 조인할 컬럼을 명시적으로 지정하자

-- DATE_FORMAT() --
DATE_FORMAT("2025-10-13", "%Y-%M-%D") >> 2022-October-13th
DATE_FORMAT("2025-10-13", "%y-%m-%d") >> 22-10-13
/*