/* 대장균의 크기에 따라 분류하기 1 */

SELECT ID, CASE 
    WHEN SIZE_OF_COLONY <= 100 THEN 'LOW' 
    WHEN SIZE_OF_COLONY >1000 THEN 'HIGH' 
    ELSE 'MEDIUM' END AS SIZE
FROM ECOLI_DATA
ORDER BY ID ASC

/* 
-- SQL_조건문 --
CASE 
    WHEN 조건1 THEN 반환1
    WHEN 조건2 THEN 반환2
    ELSE 반환3
END
*/