/* 특정 세대의 대장균 찾기*/

-- 서브쿼리를 이용한 풀이 --
SELECT ID
FROM ECOLI_DATA
WHERE PARENT_ID IN (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IN (
        SELECT ID
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NULL
    )
)
ORDER BY ID

-- JOIN을 이용한 풀이 --
SELECT G3.ID
FROM ECOLI_DATA G1 
      JOIN ECOLI_DATA G2 ON G1.ID = G2.PARENT_ID
      JOIN ECOLI_DATA G3 ON G2.ID = G3.PARENT_ID 
WHERE G1.PARENT_ID IS NULL
ORDER BY G3.ID