/* 취소되지 않은 진료 예약 조회하기 */

WITH UNCANCELED_CS_APPOINTMENT AS(
    SELECT *
    FROM APPOINTMENT
    WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' 
      AND APNT_CNCL_YN = 'N'
      AND MCDP_CD = 'CS'
)

SELECT CA.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, CA.APNT_YMD
FROM UNCANCELED_CS_APPOINTMENT CA
    JOIN PATIENT P
    ON CA.PT_NO = P.PT_NO
    JOIN DOCTOR D
    ON CA.MDDR_ID = D.DR_ID
ORDER BY CA.APNT_YMD ASC
