/* 대여 기록이 존재하는 자동차 리스트 구하기 */

-- JOIN --
SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C 
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
    ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '세단' AND MONTH(H.START_DATE) = 10
ORDER BY C.CAR_ID DESC


-- EXISTS --
SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C 
WHERE C.CAR_TYPE = '세단' AND EXISTS(
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE MONTH(START_DATE) = 10 
      AND C.CAR_ID = H.CAR_ID)
ORDER BY C.CAR_ID DESC