/* 자동차 평균 대여 기간 구하기 */

WITH CAR_RENTAL_INFO AS (
    SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT CAR_ID, ROUND(AVG(DURATION), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_INFO
GROUP BY CAR_ID HAVING AVG(DURATION) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC