/* 분기별 분화된 대장균의 개체 수 구하기 */

WITH QUARTERS AS (
    SELECT ID, PARENT_ID, SIZE_OF_COLONY, GENOTYPE,
           CASE
             WHEN MONTH(DIFFERENTIATION_DATE) IN (1,2,3) THEN '1Q'
             WHEN MONTH(DIFFERENTIATION_DATE) IN (4,5,6) THEN '2Q'
             WHEN MONTH(DIFFERENTIATION_DATE) IN (7,8,9) THEN '3Q'
             ELSE '4Q'
           END AS QUARTER 
    FROM ECOLI_DATA
)

SELECT QUARTER, COUNT(*) AS ECOLI_COUNT
FROM QUARTERS
GROUP BY QUARTER
ORDER BY QUARTER ASC
